### ISSUE TITLE
Boerewors is not a traditional Namibian Dish.

### ISSUE THREAD

**Issue by LairdStreak** [trivago/boerewors#2]
https://en.wikipedia.org/wiki/Boerewors

**Comment by bischoffdev** [comment]
"Boerewors is also very common throughout Namibia, Botswana, Mozambique and Zimbabwe[...]". So I guess you could call it traditional. It does not necessarily mean that it is ONLY associated with this region. However, this is not really an issue to be reported here unless it breaks functionality :-)
